config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Create a custom route called /levels/1/users
  # This would show all users at that level
  root 'sessions#new'

  get '/auth/:provider/callback' => 'google#create'

  get "signup" => 'users#new'
  get "login" => 'sessions#new'

  post '/sessions' => 'sessions#create'
  delete '/sessions' => 'sessions#destroy'

  resources :sessions
  resources :notes
  resources :admins
  resources :googles
  
  resources :users do
    resources :notes, shallow: true
  end
  
  resources :levels do
    resources :users
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :notes
    has_many :users, through: :notes
end

app/models/level.rb
class Level < ActiveRecord::Base
    validates :value, numericality: { less_than_or_equal: 10 }

    has_many :notes
    # Adds many-to-many relationship
    has_many :users, through: :notes, source: :creator
    has_many :targets, through: :notes, source: :target
end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :level
    belongs_to :category
    belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
    belongs_to :target, foreign_key: :target_id, class_name: 'User'

    validates :content, presence: true

    # Class level scope method
    def self.target(id)
        self.where(target_id: id)
    end
end

app/models/school.rb
class School < ActiveRecord::Base
    validates :name, uniqueness: true

    has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :email, presence: true, uniqueness: true
    validates :username, presence: true
    validates :password_digest, presence: true
    validates :name, presence: true

    has_many :created_notes, foreign_key: :creator_id, class_name: 'Note'
    has_many :notes_about_teachers, foreign_key: :target_id, class_name: 'Note'
    has_many :levels, through: :notes_about_teachers
    has_many :categories, through: :notes_about_teachers
    belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    
    def current_user
        User.find_by_id(session[:user_id])
    end
end

app/controllers/google_controller.rb
class GoogleController < ApplicationController

    def create
        @user = User.find_or_create_by(username: auth['info']['email']) do |u|
            # u.username = auth['info']['name']
            u.name = auth['info']['name']
            u.email = auth['info']['email']
            u.password = auth['uid'][-5...-1]
            u.coach = false
            u.image = auth['info']['image']
            u.school_id = 1
        end

        @user.save
        session[:user_id] = @user.id
        session[:school_id] = @user.school_id
        redirect_to user_path(@user)
    end

    def new
        render :new
    end
        
    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/notes_controller.rb
    
class NotesController < ApplicationController

    def show
        @target_user = User.find_by_id(params[:id])
    end

    def index
        @user = current_user
        @users = User.all
        if @user.coach
            @available_notes = Note.target(params[:user_id]).or(Note.all.where(target_id: @user.id)).order(id: :desc)
        else
            @available_notes = Note.target(session[:user_id]).or(Note.all.where(target_id: @user.id)).order(id: :desc)
        end
    end

    def new
        @note = Note.new
        @user = current_user
        session[:target_id] = params[:user_id].to_i
    end

    def create
        @note = Note.new(note_params)
        @levels = Level.all
        @note.creator_id = current_user.id
        @note.target_id = session[:target_id]
        if @note.valid?
            @note.save
            redirect_to user_notes_path(@note.target_id)
        else
            render :new
        end
    end

    def edit
        @note = Note.find_by_id(params[:id])
        session[:target_id] = @note.target_id
    end
    
    def update
        @note = Note.find_by_id(params[:id])
        @note.update(note_params)
        if current_user.coach
            redirect_to user_notes_path(@note.target_id)
        else
            redirect_to user_notes_path(current_user)
        end
    end

    def destroy
        @note = Note.find_by_id(params[:id])
        @note.destroy
        redirect_to user_notes_path(session[:target_id])
    end

    private

    def note_params
        params.require(:note).permit(:creator_id, :target_id, :content, :level_id, :category_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to @user
        else
            @error = 'username and password do not match our system'
            render :new
        end
    end

    def new
        @user = User.find_by_id(session[:user_id])
        if session[:user_id]
            redirect_to @user
        end
    end

    def destroy
        session.delete('user_id')
        redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create
        @user = User.new do |u|
            u.username = params[:user][:username]
            u.name = params[:user][:name]
            u.email = params[:user][:email]
            u.password = params[:user][:password]
            u.coach = false
            u.school_id = params[:user][:school_id]
            u.image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlTb6qZreuzn7kXfZd-xZsRk2WvgU4bD0ttg&usqp=CAU"
        end
        
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            session[:school_id] = @user.school_id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def new
        @user = User.new
    end

    def show
        @coach_quote_list = ["A coach is someone who can give correction without causing resentment.", "Coaches have to watch for what they don’t want to see and listen to what they don’t want to hear.", "The interesting thing about coaching is that you have to trouble the comfortable, and comfort the troubled."]
        @teacher_quote_list = ["Feedback is the breakfast of champions.", "Strive for continuous improvement, instead of perfection.", "Mistakes should be examined, learned from, and discarded; not dwelled upon and stored."]
        if session[:user_id]
            @user = current_user
            @notes = Note.all
        end
    end

    def index
        @user = current_user
        if @user.coach
            @users_at_permission_level = User.all.where(coach: false, school_id: @user.school_id).sort_by{ |obj| obj.name }
        else
            @users_at_permission_level = @user
        end
    end

    def edit
        @user = User.find_by_id(params[:id])
    end

    def update
        @user = User.find_by_id(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    def destroy
        @user = User.find_by_id(params[:id])
        @notes = Note.where(target_id: @user.id)
        @notes.each do |n|
            n.destroy
        end
        @user.destroy
        redirect_to users_path(@user)
    end


    private

    def user_params
        params.require(:user).permit(:username, :name, :email, :uid, :password_digest, :password, :coach, :school_id, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/show.html.erb
<br><br>
This is the admin show page

app/views/googles/new.html.erb
Choices

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rapport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
  <br><br>
    <% if session[:user_id] == nil %>
      <%= link_to 'Sign-Up', new_user_path %>
    <% else %>
      <%= link_to "Log Out", sessions_path, method:'delete' %> || 
      User - <%= current_user.name %>
      <% if current_user.school_id %>
       || School - <%= School.find_by_id(current_user.school_id).name %>
      <% end %>
      <img src="<%= current_user.image %>" class="profile_pic">
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/levels/index.html.erb
Hello WOrld

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
    <%= f.label :content %><br>
    <%= f.text_area :content, size: "70x5" %>
        <% if @note.errors.any? %>
            <% @note.errors.each do |e| %>
            <h5><%= e.full_message %></h5>
            <% end %>
        <% end %>
        <br>

    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name %><br>

    Priority <%= f.label :level_id %>
    <%= f.range_field :level_id, in: 1..10 %><br>
    
    
    <h3><%= f.submit %></h3>

<% end %>

app/views/notes/edit.html.erb
<br><br>
<% if current_user.coach  %>
<%= link_to 'Back', user_notes_path(session[:target_id]) %>
<% else  %>
<%= link_to 'Back', user_notes_path(current_user) %>
<% end  %>
<br><br>
<%= render :partial => 'form' %>

app/views/notes/index.html.erb
<br><br>

<% if @user.coach == true%>
<%= link_to 'Coach Someone Else', users_path %><br><br>
<% else %>
<br><%= link_to 'Back to my profile', user_path(@user) %> <br><br>  
<% end %>
<% if @user.coach %>
<h2><%= User.find_by_id(params[:user_id]).name %>'s Log</h2>
<% else %>

<h2><%= User.find_by_id(session[:user_id]).name %>'s Log</h2>
<% end %>

<%= link_to 'Add a new note', new_user_note_path %>

<% @available_notes.each do |n| %><br><br>
    <h4>Author: <%= @users.find_by_id(n.creator_id).name %></h4>
    <strong>For:</strong> <%= @users.find_by_id(n.target_id).name %><br>
    <strong>Content:</strong> <%= n.content %><br>
    <strong>Content:</strong> <%= n.category.name %><br>
    <strong>Priority:</strong> <%= n.level_id %><br>
        <% if n.creator_id == @user.id %>
            <%= link_to 'Delete', note_path(n.id), method: :delete, data: { confirm: 'Are you sure?' } %> - 
            <%= link_to 'Edit', edit_note_path(n.id), method: :get %>
        <% end %>
<% end %>

app/views/notes/new.html.erb
<br><br>
<% if current_user.coach  %>
<%= link_to 'Back', user_notes_path(session[:target_id]) %>
<% else  %>
<%= link_to 'Back', user_notes_path(current_user) %>
<% end  %>

<br><br>
<h2>Create a new note:</h2>


<%= render :partial => 'form' %>

app/views/users/edit.html.erb
<br><br>
<%= link_to 'Back to my profile', user_path(@user) %>
<h3><%= @user.name %></h3>
<%= form_for @user, html: {class: "form"} do |f| %>
		Name: <%= f.text_field :name, placeholder: "your name" %><br>
        School: <%= f.collection_select :school_id, School.all, :id, :name %><br><br>
		
        <% if current_user.coach %>
		Select if this user is a coach: <%= f.check_box :coach %><br><br>
		<% end %>

		<% if @user.errors.any? %>
            <% @user.errors.each do |e| %>
            <h5><%= e.full_message %></h5>
            <% end %>
        <% end %>
		
		<%= f.submit "Update" %>
	<% end %>

app/views/users/index.html.erb
<br><br><%= link_to 'Back to my profile', user_path(@user) %><br><br>
<h2> Start Coaching: </h2><br>

    <% @users_at_permission_level.each do |n| %>
        <%= link_to n.name, user_notes_path(n.id) %> - 
        <%= n.email %>

        <h6><%= link_to 'Delete', user_path(n.id), method: :delete, data: { confirm: 'Are you sure? All data associated with this user will be lost.' } %> - 
        <%= link_to 'Edit', edit_user_path(n.id), method: :get %></h6><br><br>
    <% end %>

app/views/users/new.html.erb
<br>
<%= link_to 'Back to Sign-In', root_path %>
<br><br>
<h3>Sign Up</h3>
	<%= form_for @user, html: {class: "form"} do |f| %>
		<%= f.text_field :email, placeholder: "email" %><br><br>
		<%= f.text_field :username, placeholder: "username" %><br><br>
		<%= f.text_field :name, placeholder: "your name" %><br><br>
		<%= f.password_field :password, placeholder: "password" %><br><br>
		School: <%= f.collection_select :school_id, School.all, :id, :name %><br><br>
		
		
		<% if @user.errors.any? %>
            <% @user.errors.each do |e| %>
            <h5><%= e.full_message %></h5>
            <% end %>
        <% end %>
		
		<%= f.submit "Sign-Up" %>
	<% end %>

app/views/users/show.html.erb
<br><br><%= link_to 'Edit my Profile', edit_user_path(@user.id), method: :get %>
<br><br>
<h1>Welcome <%= current_user.name %>
    <% if @user.coach == true %>
        <%= " -- Coach" %></h1><br><br>
        <h4><%= @coach_quote_list.sample %></h4>
        <a href= <%=users_path%> class='button'>Get Started<a>
    <% else %>
        <%= " -- Teacher" %></h1><br><br>
        <h4><%= @teacher_quote_list.sample %></h4>
        <a href= <%=user_notes_path(@user.id)%> class='button'>Take a look at your coaching log<a>
    <% end %>
<br><br>